Added method to load / save from arbitrary target, not only files
bodoni/svg pull request #5
Opened 2017-06-22 20:26 UTC by sharazam

Added `open_from()` and `save_to` methods to load anything that implements `std::io::Read`. Does not break existing code. Needed for streaming SVG / being generic over the input method.

2017-06-23 11:18 UTC, IvanUkhov requested changes
Thank you for the useful addition! Please address my feedback.

2017-06-23 11:18 UTC, IvanUkhov commented on src/lib.rs
> +use std::io::{Read, Write};
Merge this one with `use std::io` above.

2017-06-23 11:18 UTC, IvanUkhov commented on src/lib.rs
> +//! use std::fs::File;
Put it before the group of `use`s above.

2017-06-23 11:18 UTC, IvanUkhov commented on src/lib.rs
> +pub fn open<'l, P>(path: P) -> io::Result<Parser<'l>> where P: AsRef<Path> {
Revert it back to `T`.

2017-06-23 11:18 UTC, IvanUkhov commented on src/lib.rs
> +/// Open a document from a path
Add a period.

2017-06-23 11:18 UTC, IvanUkhov commented on src/lib.rs
> +/// Open a document from an arbitrary source
Add a period.

2017-06-23 11:18 UTC, IvanUkhov commented on src/lib.rs
> +pub fn open_from<'l, R>(source: R) -> io::Result<Parser<'l>> where R: Read {
Rename to `read` and use `T` instead of `R`.

2017-06-23 11:18 UTC, IvanUkhov commented on src/lib.rs
> +/// Save a document to a path
Add a period.

2017-06-23 11:18 UTC, IvanUkhov commented on src/lib.rs
> +pub fn save<'l, P, U>(path: P, document: &U) -> io::Result<()> where P: AsRef<Path>, U: Node{
Remove `'l`, revert to `T`, and add a space after `Node`.

2017-06-23 11:18 UTC, IvanUkhov commented on src/lib.rs
> +fn open_internal<'l, R>(mut source: R) -> io::Result<Parser<'l>> where R: Read {
Rename to `read_internal`.

2017-06-23 11:18 UTC, IvanUkhov commented on src/lib.rs
> +pub fn save_to<'l, W, U>(target: W, document: &U) -> io::Result<()> where W: Write, U: Node {
Rename to `write`, remove `'l`, and use `T` instead of `W`.

2017-06-23 11:18 UTC, IvanUkhov commented on src/lib.rs
> +fn save_internal<W, U>(mut target: W, document: &U) -> io::Result<()> where W: Write, U: Node {
Rename to `write_internal` and use `T` instead of `W`.

2017-06-23 11:18 UTC, IvanUkhov commented on src/lib.rs
> +        let _ = ::open_from(&mut File::open(TEST_PATH).unwrap());
Create a separate test called `read`.

2017-06-23 16:30 UTC, IvanUkhov commented
This code is in a way redundant because all the interfaces that `load` and `save` are using right now are public. One doesn’t have to work with files. If the content to parse is already in memory, one can instantiate `Parser` directly. Similarly, if the content is to be stored in memory, one can just rely on `Display` to that end. However, these two new functions, `read` and `write`, might be useful in order to make it more obvious. They can be handy shortcuts just as `load` and `save` are.

2017-06-23 16:34 UTC, IvanUkhov commented on src/lib.rs
> +/// Open a document from a path
And actually remove “from a path”.

2017-06-23 16:34 UTC, IvanUkhov commented on src/lib.rs
> +/// Save a document to a path
And actually remove “to a path”.

2017-06-23 16:35 UTC, IvanUkhov commented on src/lib.rs
> +/// Open a document from an arbitrary source
And actually change to just “Read a document.”

2017-06-23 16:36 UTC, IvanUkhov commented on src/lib.rs
> +pub fn save_to<'l, W, U>(target: W, document: &U) -> io::Result<()> where W: Write, U: Node {
And actually change the description to “Write a document.”

2017-07-03 08:44 UTC, sharazam commented
Should have fixed the styling issues. No idea how to test the save method, there's no documentation on how to actually get "Node" elements. Somehow I need a Node, which is only implemented for Element, but I can't get any elements from the read document, only "Events" - it's a convoluted mess.

If you could fix that, that'd be great, because I don't know how to read a document and then immediately save it again, the documentation isn't clear enough.

2017-07-03 08:49 UTC, merged

2017-07-03 09:08 UTC, IvanUkhov commented
Thanks for your work!

Regarding `save`, I’m not sure why you wanted to test it as technically you hadn’t touched it. Did you mean `write`? In any case, `Node` is [implemented for a bunch of structs](https://docs.rs/svg/0.5.5/svg/node/trait.Node.html), and you can create an `Element` yourself as it is [shown in the first example](https://docs.rs/svg/0.5.5/svg/index.html#example-composing) given in the documentation. Or have I misunderstood you?